### ISSUE TITLE
Error while using non-live shuffler

### ISSUE THREAD

**Issue by oneup40** [krelbel/ALttPMSUShuffler#5]
`cooldown` needs to be set to `int(live)` only if the live shuffler is being used, otherwise it raises an Exception if `live` is `None`:

```
>py Main.py
ALttPMSUShuffler version 0.8.2
Reusing track index, run with --reindex to pick up any new packs.
Non-looping tracks:
Traceback (most recent call last):
  File "C:\Users\Oneup\Downloads\msu\prep\ALttPMSUShuffler-master\Main.py", line 709, in <module>
    main(args)
  File "C:\Users\Oneup\Downloads\msu\prep\ALttPMSUShuffler-master\Main.py", line 662, in main
    generate_shuffled_msu(args, rom)
  File "C:\Users\Oneup\Downloads\msu\prep\ALttPMSUShuffler-master\Main.py", line 638, in generate_shuffled_msu
    shuffle_all_tracks(rompath, args.fullshuffle, args.singleshuffle, args.dry_run, args.higan, args.forcerealcopy, args.live, args.nowplaying, 0, 0)
  File "C:\Users\Oneup\Downloads\msu\prep\ALttPMSUShuffler-master\Main.py", line 455, in shuffle_all_tracks
    cooldown = int(live)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by oneup40** [comment]
link to PR: https://github.com/krelbel/ALttPMSUShuffler/pull/6

**Comment by krelbel** [comment]
merged, thanks for the fix
